# Generated by Django 5.2.6 on 2025-11-23 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_email_alter_like_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': '좋아요', 'verbose_name_plural': '좋아요 목록'},
        ),
        migrations.AddField(
            model_name='like',
            name='receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='received_likes', to=settings.AUTH_USER_MODEL, verbose_name='좋아요를 받은 사용자'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('liker', 'receiver')},
        ),
        migrations.AlterField(
            model_name='like',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='좋아요 시간'),
        ),
        migrations.AlterField(
            model_name='like',
            name='liker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_likes', to=settings.AUTH_USER_MODEL, verbose_name='좋아요를 준 사용자'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='나이'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default=1, max_length=500, verbose_name='자기소개'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', '남성'), ('female', '여성'), ('other', '기타')], default='', max_length=10, verbose_name='성별'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='interests',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='관심사'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='닉네임'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='profile_pics/default.jpg', max_length=500, upload_to='profile_pics', verbose_name='프로필 사진'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='업데이트일'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.RemoveField(
            model_name='like',
            name='liked',
        ),
    ]


